### ISSUE TITLE
作者你真睿智！

### ISSUE THREAD

**Issue by NaroisCool** [tianqiraf/DouZero_for_JJ#35]
佩服作者没有把真正的源码公布，不然相当于写了个外挂流入市场，仔细看了一边代码逻辑，很多地方代码是错的，或者数据位置不对。反正小白白嫖是没戏。

**Comment by onedayday-wb** [comment]
> 佩服作者没有把真正的源码公布，不然相当于写了个外挂流入市场，仔细看了一边代码逻辑，很多地方代码是错的，或者数据位置不对。反正小白白嫖是没戏。

我说呢，等所有的牌都显示完整了，点击开始都没有任何报错就直接闪退了，一脸懵逼，兄弟能告知一二吗？python不是很熟悉，不知道怎么修改

**Comment by yz1639** [comment]
我感觉你有点逗，开源是种精神。python的项目所见即所得。何来`真正的源码`

- `代码是错的`
- `数据位置不对`

如果是这样一开始就不会运行起来，或者运行起来也是没效果的，就没考虑过游戏更新后导致的兼容问题？

我期待您的`fix`版本, 而不是在这阴阳怪气
